# Generated by Django 4.2.4 on 2023-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
