# Generated by Django 4.2.4 on 2023-09-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_video_description_remove_video_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
    ]
