# Generated by Django 4.2.4 on 2023-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='big_preview',
            field=models.ImageField(height_field=80, upload_to='images/', width_field=120),
        ),
        migrations.AlterField(
            model_name='video',
            name='small_prewiew',
            field=models.ImageField(height_field=40, upload_to='images/', width_field=60),
        ),
    ]
