# Generated by Django 4.2.4 on 2023-09-29 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='big_preview',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='small_prewiew',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
