# Generated by Django 4.2.4 on 2023-09-29 21:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_remove_video_big_preview_remove_video_lesson_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='video',
            name='lesson_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
            preserve_default=False,
        ),
    ]
