# Generated by Django 4.2.4 on 2023-09-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_delete_image_video_lesson_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
