# Generated by Django 4.2.4 on 2023-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_bio_alter_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aim',
            field=models.TextField(blank=True, default=''),
        ),
    ]
